import{S as h,i as d,a as g}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const y=new h(".gallery a",{captionDelay:250,captionsData:"alt"});function L(t){const{largeImageURL:r,webformatURL:a,tags:c,likes:e,views:o,comments:s,downloads:f}=t;return`<li class="photos-list-item">
  <a class="photos-list-link" href="${r}">
  <img loading="lazy" class="photo" src="${a}" alt="${c}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${o}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${s}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${f}</p></li>
  </ul>
  </li>`}function b(t){return t.length===0&&d.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),t.map(L).join("")}function p(t){const r=b(t);n.gallery.insertAdjacentHTML("beforeend",r),y.refresh()}n.loader.style.display="none";const F="https://pixabay.com/api/",w="43014445-2d3e2fe82a6f953d204684055";async function m(t,r){try{return(await g.get(F,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,perPage:15,page:r}})).data}catch(a){throw console.error("Error:",a),a}}const n={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".btn-footer-form"),loader:document.querySelector(".loader")};let l,i=1,u=0;const S=15;n.form.addEventListener("submit",M);async function M(t){if(t.preventDefault(),l=t.target.elements.query.value.trim(),n.gallery.innerHTML="",i=1,!l){d.error({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}const r=await m(l,i);u=Math.ceil(r.totalHits/S),p(r.hits),E(),t.target.reset()}n.btnLoadMore.addEventListener("click",P);async function P(){i+=1;const t=await m(l,i);p(t.hits)}function q(){n.btnLoadMore.classList.remove("hidden")}function v(){n.btnLoadMore.classList.add("hidden")}function E(){i>=u?v():q()}
//# sourceMappingURL=commonHelpers.js.map
