import{a as w,S,i}from"./assets/vendor-550cebad.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/",E="43014445-2d3e2fe82a6f953d204684055";async function m(e,o){try{return(await w.get(v,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch(s){throw console.error("Error:",s),s}}const P=new S(".gallery a",{captionDelay:250,captionsData:"alt"});function q(e){const{largeImageURL:o,webformatURL:s,tags:c,likes:t,views:r,comments:a,downloads:b}=e;return`<li class="photos-list-item">
  <a class="photos-list-link" href="${o}">
  <img loading="lazy" class="photo" src="${s}" alt="${c}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${a}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${b}</p></li>
  </ul>
  </li>`}function C(e){return e.map(q).join("")}function f(e){const o=C(e);p.insertAdjacentHTML("beforeend",o),P.refresh()}const R=document.querySelector(".form"),p=document.querySelector(".gallery"),h=document.querySelector(".btn-footer-form"),g=document.querySelector(".loader");function y(){g.classList.remove("is-hidden")}function d(){g.classList.add("is-hidden")}function B(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}let l,n=1,F=0;const k=15;R.addEventListener("submit",M);async function M(e){if(e.preventDefault(),u(),y(),p.innerHTML="",n=1,l=e.target.elements.query.value.trim(),!l){i.error({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),d();return}try{const o=await m(l,n);F=Math.ceil(o.totalHits/k),o.hits.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}):(f(o.hits),L())}catch(o){console.log(o),i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}d(),e.target.reset()}h.addEventListener("click",$);async function $(){n+=1,u(),y();try{const e=await m(l,n);f(e.hits)}catch(e){console.log(e),i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}O(),L(),d()}function L(){n>=F?(u(),i.error({message:"We're sorry, but you've reached the end of search results.",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})):B()}function O(){const e=p.firstChild.getBoundingClientRect().height;scrollBy({top:e*3,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
