import{a as p}from"./assets/vendor-34f890c2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const r of e.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const d="https://pixabay.com/api/",h="43014445-2d3e2fe82a6f953d204684055";async function y(n,o){try{return(await p.get(d,{params:{key:h,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,perPage:15,page:o}})).data}catch(s){throw console.error("Error:",s),s}}const g="modulepreload",v=function(n){return"/goit-js-hw-12/"+n},m={},w=function(o,s,a){if(!s||s.length===0)return o();const t=document.getElementsByTagName("link");return Promise.all(s.map(e=>{if(e=v(e),e in m)return;m[e]=!0;const r=e.endsWith(".css"),u=r?'[rel="stylesheet"]':"";if(!!a)for(let c=t.length-1;c>=0;c--){const l=t[c];if(l.href===e&&(!r||l.rel==="stylesheet"))return}else if(document.querySelector(`link[href="${e}"]${u}`))return;const i=document.createElement("link");if(i.rel=r?"stylesheet":g,r||(i.as="script",i.crossOrigin=""),i.href=e,document.head.appendChild(i),r)return new Promise((c,l)=>{i.addEventListener("load",c),i.addEventListener("error",()=>l(new Error(`Unable to preload CSS for ${e}`)))})})).then(()=>o()).catch(e=>{const r=new Event("vite:preloadError",{cancelable:!0});if(r.payload=e,window.dispatchEvent(r),!r.defaultPrevented)throw e})};w(()=>import(f),[]);function E(n){const{largeImageURL:o,webformatURL:s,tags:a,likes:t,views:e,comments:r,downloads:u}=n;return`<li class="photos-list-item">
  <a class="photos-list-link" href="${o}">
  <img loading="lazy" class="photo" src="${s}" alt="${a}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${u}</p></li>
  </ul>
  </li>`}function L(n){return n.map(E).join("")}function b(n){const o=L(n);f.gallery.insertAdjacentHTML("beforeend",o)}const f={form:document.querySelector(".form"),gallery:document.querySelector(".gallery")};f.form.addEventListener("submit",P);async function P(n){n.preventDefault();const o=n.target.elements.query.value.trim(),s=await y(o,1);b(s.hits)}
//# sourceMappingURL=commonHelpers.js.map
